global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'student_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['student-service:8080']
        labels:
          application: 'Student Service Application'
  - job_name: 'group_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['group-service:8080']
        labels:
          application: 'Group Service Application'
  - job_name: 'check_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['check-service:8080']
        labels:
          application: 'Check Service Application'
  - job_name: 'notification_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8080']
        labels:
          application: 'Notification Service Application'
  - job_name: 'grade_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'grade-service:8080' ]
        labels:
          application: 'Grade Service Application'
